### ISSUE TITLE
Resolve a security issue

### ISSUE THREAD

**Issue by sehkone** [aicers/roxy#350]
According to [this](https://github.com/aicers/roxy/security/dependabot/4), we need to update `hashbrown` by updating `serde-with`.

**Comment by danbi2990** [comment]
`serde-with` has pinned the version of `hashbrown` to 0.15.0.
(See [Cargo.toml#L135](https://github.com/jonasbb/serde_with/blob/master/serde_with/Cargo.toml#L135).)
This is expected to be resolved once `serde-with` upgrades its dependency.
I will monitor the progress and follow up accordingly.

**Comment by danbi2990** [comment]
This issue has been fixed by #353.
@sehkone Could you confirm and close it?

**Comment by sehkone** [comment]
> This issue has been fixed by #353. @sehkone Could you confirm and close it?

Got it.
